### ISSUE TITLE
The adobe color link in README return a 404

### ISSUE THREAD

**Issue by PierreLeresteux** [quantixx/template-presentation#2]
The proposed link https://color.adobe.com/fr/Mon-th%C3%A8me-Color-color-theme-12221805/? for Adobe color returns a 404 error page.

I see a lot of Devoxx theme in this website : https://color.adobe.com/fr/search?q=devoxx but not sure to select the correct one.

**Comment by nicmarti** [comment]
Thanks, this was for 2019 and it's not relevant anymore. I close the issue
